# Generated by Django 2.1.2 on 2018-10-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('tv_id', models.IntegerField(blank=True)),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'favorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('friend_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('to_user', models.IntegerField(blank=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'friend_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('friendship_id', models.AutoField(primary_key=True, serialize=False)),
                ('user2', models.IntegerField(blank=True)),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'friendship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('seen', models.BooleanField(blank=True)),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('notification_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=85, null=True)),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
